version: '3.9'
services:
  minio:
    image: quay.io/minio/minio
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password

  api:
    build: ../backend
    ports:
      - "8000:8000"
    depends_on:
      - minio

  frontend:
    build: ../frontend
    ports:
      - "3000:80"
    depends_on:
      - api
